In [1]:
import numpy as np

In [2]:
data1 = [5, 7, 9, 20]    #列表
arr1 = np.array(data1)
arr1

array([ 5,  7,  9, 20])

In [3]:
data2 = (5, 7, 9, 20)     #元组
arr2 = np.array(data2)
arr2

array([ 5,  7,  9, 20])

In [4]:
data3 = [[1, 2, 3, 4],[5, 6, 7, 8]]   #多维数组
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr3.shape

(2, 4)

In [6]:
arr3.dtype

dtype('int32')

In [7]:
data4 = [1.2, 2, 3.45, 5]
arr4 = np.array(data4)
arr4

array([ 1.2 ,  2.  ,  3.45,  5.  ])

In [8]:
arr4.dtype

dtype('float64')

In [9]:
np.zeros(8)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [11]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [12]:
np.ones((4,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [13]:
np.empty((2, 2, 2))

array([[[  8.25089629e-322,   2.39127773e-321],
        [  2.47032823e-323,   3.90344271e-316]],

       [[  0.00000000e+000,   2.47032823e-323],
        [  3.90350911e-316,   0.00000000e+000]]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr5 = np.ones_like(arr3)
arr5

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
arr5.dtype

dtype('int32')

In [19]:
data = [[2, 4, 5],[3,5, 7]]
arr = np.array(data)
arr

array([[2, 4, 5],
       [3, 5, 7]])

In [20]:
arr.ndim

2

In [21]:
arr.size

6

In [22]:
arr.itemsize

4

In [23]:
arr.dtype

dtype('int32')

In [26]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [27]:
arr1.dtype

dtype('int32')

In [28]:
arr2 = np.arange(5,dtype='float64')
arr2

array([ 0.,  1.,  2.,  3.,  4.])

In [29]:
arr2.dtype

dtype('float64')

In [31]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [32]:
arr1.dtype

dtype('int32')

In [33]:
arr2 = arr1.astype(np.float64)
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.])

In [34]:
arr2.dtype

dtype('float64')

In [35]:
arr3 = arr1.astype('string_')
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'],
      dtype='|S11')

In [36]:
arr3.dtype

dtype('S11')

In [38]:
arr = np.array([2.3, 7.5, 5.6, 9.8])
arr

array([ 2.3,  7.5,  5.6,  9.8])

In [39]:
arr.astype('int32')

array([2, 7, 5, 9])

In [40]:
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'],
      dtype='|S11')

In [42]:
arr3.astype(np.int32)

array([0, 1, 2, 3, 4, 5])

In [43]:
arr = np.array(['2', 'hello'])
arr

array(['2', 'hello'],
      dtype='<U5')

In [44]:
arr.astype('int32')

ValueError: invalid literal for int() with base 10: 'hello'

In [45]:
arr1 = np.arange(10)
arr1.dtype

dtype('int32')

In [46]:
arr2 = np.ones(5)
arr2.dtype

dtype('float64')

In [47]:
arr3 = arr1.astype(arr2.dtype)
arr3.dtype

dtype('float64')

In [48]:
arr = np.arange(3)
arr.dtype

dtype('int32')

In [49]:
arr.astype('float64')

array([ 0.,  1.,  2.])

In [50]:
arr

array([0, 1, 2])

# 数据重塑合并

In [51]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr = np.array([[3, 4, 5],[1, 2, 3]])
arr.reshape((3,2))

array([[3, 4],
       [5, 1],
       [2, 3]])

In [55]:
arr = np.arange(12)
arr.reshape((3,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
arr = np.arange(10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [60]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
arr2 = np.arange(12,24).reshape(3,4)
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
np.concatenate([arr1, arr2],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
np.concatenate([arr1, arr2],axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [73]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
np.hstack((arr1, arr2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [76]:
arr = np.arange(12).reshape((6,2))
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [77]:
np.split(arr,[2, 4])

[array([[0, 1],
        [2, 3]]), array([[4, 5],
        [6, 7]]), array([[ 8,  9],
        [10, 11]])]

In [78]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
arr.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [80]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [81]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [82]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 随机数

In [85]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[168, 180, 142, 134],
       [100, 106, 107, 147],
       [125, 170, 117, 192],
       [194, 172, 173, 102],
       [171, 171, 193, 180]])

In [87]:
arr = np.random.randn(2, 3, 5)
arr

array([[[-0.23022075, -1.53376604, -1.20506611, -0.72058013,  1.69808677],
        [-1.62102742, -1.1053548 ,  0.76182009, -1.24876097, -1.55001938],
        [ 0.04078704,  1.96669076, -2.24999391, -1.08302149,  0.52640131]],

       [[ 0.09381983,  1.16288913, -0.15885707,  0.93718335, -0.72444705],
        [-1.68017525, -0.18660456,  0.01881962,  0.16711124, -1.60857221],
        [ 0.93210884, -0.26899384, -0.35037258, -0.404521  ,  1.07034161]]])

In [88]:
arr = np.random.normal(4, 5, size=(3,5))
arr

array([[  8.29188165,  -6.11855239,  -1.5724349 ,   6.97515202,
          3.83049015],
       [  2.23989149,   7.81287044, -10.01907046,   3.68896253,
          3.01140917],
       [ 10.68983039,   7.63279875,  10.70678635,   2.66406148,
          3.76512045]])

In [89]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[147, 122, 130, 169],
       [151, 152, 117, 119],
       [129, 140, 111, 131],
       [197, 126, 176, 199],
       [128, 174, 117, 143]])

In [90]:
np.random.permutation(arr)

array([[151, 152, 117, 119],
       [197, 126, 176, 199],
       [128, 174, 117, 143],
       [147, 122, 130, 169],
       [129, 140, 111, 131]])

In [91]:
arr

array([[147, 122, 130, 169],
       [151, 152, 117, 119],
       [129, 140, 111, 131],
       [197, 126, 176, 199],
       [128, 174, 117, 143]])

In [92]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[196, 140, 199, 182],
       [161, 109, 193, 176],
       [102, 138, 165, 166],
       [191, 181, 108, 113],
       [168, 102, 199, 150]])

In [93]:
np.random.shuffle(arr)

In [94]:
arr

array([[168, 102, 199, 150],
       [191, 181, 108, 113],
       [102, 138, 165, 166],
       [161, 109, 193, 176],
       [196, 140, 199, 182]])

# 索引和切片

In [1]:
import numpy as np

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[3]

3

In [17]:
arr[-1]

9

In [18]:
arr[2] = 123
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [19]:
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [20]:
arr[3] = 88
arr

array([  0,   1, 123,  88,   4,   5,   6,   7,   8,   9])

In [22]:
arr1 = arr[-3:-1]
arr1

array([7, 8])

In [23]:
arr1[:] = 77
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [24]:
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [26]:
arr1 = arr[1].copy()
arr1 = 34
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [27]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr[0]

array([0, 1, 2, 3, 4])

In [29]:
arr[2]

array([10, 11, 12, 13, 14])

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
arr[0][3]

3

In [32]:
arr[2,3]  #两种方法等价

13

In [33]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [34]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
old = arr[0].copy()
arr[0] = 12
arr

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
arr[0] = old
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [37]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [38]:
arr[1, 1]

array([ 9, 10, 11])

In [39]:
arr[0, 1, 2]

5

In [40]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [41]:
arr[2:5]

array([2, 3, 4])

In [42]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
arr[2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
arr[:, 1]

array([ 1,  4,  7, 10])

In [47]:
arr[:, 1:2]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [49]:
arr[2:, 1:]

array([[ 7,  8],
       [10, 11]])

In [56]:
fruits = np.array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'])
datas = np.random.randint(-1, 1, size=(7,5))

In [57]:
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [58]:
datas

array([[ 0, -1,  0,  0, -1],
       [-1, -1,  0,  0, -1],
       [-1,  0, -1, -1,  0],
       [-1,  0,  0, -1,  0],
       [ 0,  0,  0,  0, -1],
       [-1, -1,  0,  0,  0],
       [ 0,  0, -1,  0, -1]])

In [59]:
fruits == 'pear'

array([False, False,  True, False,  True, False,  True], dtype=bool)

In [60]:
datas[fruits == 'pear']

array([[-1,  0, -1, -1,  0],
       [ 0,  0,  0,  0, -1],
       [ 0,  0, -1,  0, -1]])

In [61]:
datas[fruits != 'pear']

array([[ 0, -1,  0,  0, -1],
       [-1, -1,  0,  0, -1],
       [-1,  0,  0, -1,  0],
       [-1, -1,  0,  0,  0]])

In [62]:
datas[(fruits == 'apple') | (fruits == 'banana')]

array([[ 0, -1,  0,  0, -1],
       [-1, -1,  0,  0, -1],
       [-1,  0,  0, -1,  0],
       [-1, -1,  0,  0,  0]])

In [63]:
datas[fruits == 'pear',2:]

array([[-1, -1,  0],
       [ 0,  0, -1],
       [-1,  0, -1]])

In [64]:
datas[fruits == 'pear',2]

array([-1,  0, -1])

In [66]:
datas[datas == 0] = 1
datas

array([[ 1, -1,  1,  1, -1],
       [-1, -1,  1,  1, -1],
       [-1,  1, -1, -1,  1],
       [-1,  1,  1, -1,  1],
       [ 1,  1,  1,  1, -1],
       [-1, -1,  1,  1,  1],
       [ 1,  1, -1,  1, -1]])

In [67]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
arr[[1, 3, 2]]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 6,  7,  8]])

In [70]:
arr[[3, 2]][:, [2, 1]]

array([[11, 10],
       [ 8,  7]])

In [71]:
arr[np.ix_([3,2],[2, 1])]

array([[11, 10],
       [ 8,  7]])

In [72]:
a = [1, 2, 3]
b = []
for i in a:
    b.append(i * 10)
b

[10, 20, 30]

In [73]:
arr = np.array([1, 2, 3])
arr * 10

array([10, 20, 30])

In [74]:
arr * arr

array([1, 4, 9])

In [75]:
arr - arr

array([0, 0, 0])

In [77]:
arr = np.random.randn(3,3)
arr

array([[-1.30289625, -1.62082859, -0.02086977],
       [ 0.61681656,  1.44215576,  1.7281482 ],
       [-0.96761142,  0.6475979 , -0.57524988]])

In [78]:
np.abs(arr)

array([[ 1.30289625,  1.62082859,  0.02086977],
       [ 0.61681656,  1.44215576,  1.7281482 ],
       [ 0.96761142,  0.6475979 ,  0.57524988]])

In [79]:
np.square(arr)

array([[  1.69753863e+00,   2.62708531e+00,   4.35547217e-04],
       [  3.80462668e-01,   2.07981323e+00,   2.98649619e+00],
       [  9.36271853e-01,   4.19383043e-01,   3.30912420e-01]])

In [82]:
arr1 = np.random.randint(1, 10, size=(5))
arr1

array([5, 2, 9, 4, 1])

In [83]:
arr2 = np.random.randint(1, 10, size=(5))
arr2

array([7, 6, 9, 1, 3])

In [84]:
np.add(arr1, arr2)

array([12,  8, 18,  5,  4])

In [85]:
np.minimum(arr1, arr2)

array([5, 2, 9, 1, 1])

In [86]:
arr = np.random.normal(2,4,size=(6,))
arr

array([ 4.03156633,  2.24471147, -1.05295999,  3.17361538,  9.45900887,
        2.48014303])

In [87]:
np.modf(arr)

(array([ 0.03156633,  0.24471147, -0.05295999,  0.17361538,  0.45900887,
         0.48014303]), array([ 4.,  2., -1.,  3.,  9.,  2.]))

In [88]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
cond = np.array([True, False, False, True])

In [89]:
result = [(x if c else y) for x, y, c in zip(arr1, arr2, cond)]
result

[1, 6, 7, 4]

In [91]:
result = np.where(cond, arr1, arr2)
result

array([1, 6, 7, 4])

In [93]:
arr = np.random.randn(4, 4)
arr

array([[ 0.99483299, -0.42559031,  0.60728194, -0.28477079],
       [-0.47341549, -1.03284446, -1.24692688, -0.7168212 ],
       [-0.2463296 ,  0.9006737 , -0.8362647 ,  0.28860023],
       [ 0.24025673, -1.14644973,  0.84133157, -0.00742223]])

In [94]:
new_arr = np.where(arr > 0, 1, -1)
new_arr

array([[ 1, -1,  1, -1],
       [-1, -1, -1, -1],
       [-1,  1, -1,  1],
       [ 1, -1,  1, -1]])

In [115]:
arr = np.random.randint(1, 300, size=(3,3))
arr

array([[177, 177,  99],
       [238, 233, 131],
       [125, 288,   5]])

In [116]:
new_arr = np.where(arr > 200, 3,
                   np.where(arr > 100, 2, 1))
new_arr

array([[2, 2, 1],
       [3, 3, 2],
       [2, 3, 1]])

In [121]:
arr = np.random.randn(4, 4)
arr

array([[-0.2460958 , -3.56262609,  2.28878812, -0.66155659],
       [-0.32224876, -0.62264566,  0.0759868 , -0.50014849],
       [ 0.38841614,  0.2260369 , -0.61771424,  0.00538855],
       [-0.29865896,  0.51231692,  0.48119231,  0.06256321]])

In [122]:
arr.sum()

-2.791005624657537

In [123]:
arr.mean()

-0.17443785154109606

In [124]:
arr.std()

1.1141240674492316

In [125]:
arr

array([[-0.2460958 , -3.56262609,  2.28878812, -0.66155659],
       [-0.32224876, -0.62264566,  0.0759868 , -0.50014849],
       [ 0.38841614,  0.2260369 , -0.61771424,  0.00538855],
       [-0.29865896,  0.51231692,  0.48119231,  0.06256321]])

In [126]:
arr.mean(axis=1)

array([ -5.45372587e-01,  -3.42264027e-01,   5.31836566e-04,
         1.89353371e-01])

In [127]:
arr.sum(0)

array([-0.47858738, -3.44691793,  2.228253  , -1.09375332])

In [128]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [130]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [132]:
arr = np.random.randn(20)
arr

array([ 0.64854453, -1.02444099,  1.18506546,  1.0588872 , -1.67297679,
        1.11245385, -1.47720606,  0.67531455,  0.10707936,  1.60181681,
       -0.09663766,  0.13821122,  2.08949018, -0.85208144, -1.01504574,
       -1.01749498,  0.42782922, -0.83512655,  0.20623175, -0.23411408])

In [133]:
(arr > 0).sum()

11

In [134]:
arr = np.array([True, False, False, True])
arr

array([ True, False, False,  True], dtype=bool)

In [135]:
arr.any()

True

In [136]:
arr.all()

False

In [137]:
arr = np.random.randn(10)
arr

array([-0.06763165,  0.70670621, -2.28090762,  0.61654106,  0.35562341,
        0.57962632,  0.09817634,  1.52590085,  0.24640778, -0.69223728])

In [139]:
arr.sort()
arr

array([-2.28090762, -0.69223728, -0.06763165,  0.09817634,  0.24640778,
        0.35562341,  0.57962632,  0.61654106,  0.70670621,  1.52590085])

In [140]:
arr = np.random.randn(5,3)
arr

array([[ 0.76464658,  1.03958729,  0.83151511],
       [ 1.63188956, -0.62708685,  0.05175314],
       [ 0.85665906, -0.24305887,  1.30020042],
       [ 2.00108815, -1.49244044, -0.06771401],
       [ 0.26482398, -1.42061605, -1.0372988 ]])

In [141]:
arr.sort(1)
arr

array([[ 0.76464658,  0.83151511,  1.03958729],
       [-0.62708685,  0.05175314,  1.63188956],
       [-0.24305887,  0.85665906,  1.30020042],
       [-1.49244044, -0.06771401,  2.00108815],
       [-1.42061605, -1.0372988 ,  0.26482398]])

In [142]:
fruits = np.array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'])
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [144]:
np.unique(fruits)

array(['apple', 'banana', 'pear'],
      dtype='<U6')

In [145]:
arr = np.array([2, 3, 3, 2, 8, 1])
arr

array([2, 3, 3, 2, 8, 1])

In [146]:
np.unique(arr)

array([1, 2, 3, 8])

In [147]:
arr = np.array([2, 3, 5, 7])
arr

array([2, 3, 5, 7])

In [148]:
np.in1d(arr, [2,7])

array([ True, False, False,  True], dtype=bool)

In [149]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [152]:
np.savetxt('ch2ex1.csv', arr, fmt='%d',delimiter=',')

In [153]:
!type ch2ex1.csv

0,1,2
3,4,5
6,7,8
9,10,11


In [155]:
arr = np.loadtxt('ch2ex1.csv', delimiter=',')
arr

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.]])

In [156]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [159]:
np.dot(arr1,arr2)

array([[24, 30, 36],
       [51, 66, 81]])

In [160]:
from numpy.linalg import det

In [161]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [162]:
det(arr)

-2.0000000000000004

# 图像处理

In [164]:
from PIL import Image
import numpy as np

In [165]:
im = np.array(Image.open('C:/Users/LP/Desktop/2.76.jpeg'))
print(im.shape,im.dtype)

(350, 583, 3) uint8


In [166]:
im

array([[[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ..., 
        [198, 198, 198],
        [197, 197, 197],
        [196, 196, 196]],

       [[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ..., 
        [198, 198, 198],
        [197, 197, 197],
        [196, 196, 196]],

       [[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ..., 
        [198, 198, 198],
        [197, 197, 197],
        [195, 195, 195]],

       ..., 
       [[210, 210, 210],
        [211, 211, 211],
        [211, 211, 211],
        ..., 
        [122, 122, 122],
        [124, 124, 124],
        [125, 125, 125]],

       [[211, 211, 211],
        [211, 211, 211],
        [211, 211, 211],
        ..., 
        [120, 120, 120],
        [122, 122, 122],
        [124, 124, 124]],

       [[211, 211, 211],
        [211, 211, 211],
        [212, 212, 212],
        ..., 
        [119, 119, 119],
        [121, 121, 121],
        [123, 123,

In [170]:
b = [255, 255, 255] - im    #数组运算
new_im = Image.fromarray(b.astype('uint8'))  
new_im.save('C:/Users/LP/Desktop/2.79.jpeg')  #保存为新图像

In [172]:
b

array([[[ 29,  29,  29],
        [ 29,  29,  29],
        [ 29,  29,  29],
        ..., 
        [ 57,  57,  57],
        [ 58,  58,  58],
        [ 59,  59,  59]],

       [[ 29,  29,  29],
        [ 29,  29,  29],
        [ 29,  29,  29],
        ..., 
        [ 57,  57,  57],
        [ 58,  58,  58],
        [ 59,  59,  59]],

       [[ 29,  29,  29],
        [ 29,  29,  29],
        [ 29,  29,  29],
        ..., 
        [ 57,  57,  57],
        [ 58,  58,  58],
        [ 60,  60,  60]],

       ..., 
       [[ 45,  45,  45],
        [ 44,  44,  44],
        [ 44,  44,  44],
        ..., 
        [133, 133, 133],
        [131, 131, 131],
        [130, 130, 130]],

       [[ 44,  44,  44],
        [ 44,  44,  44],
        [ 44,  44,  44],
        ..., 
        [135, 135, 135],
        [133, 133, 133],
        [131, 131, 131]],

       [[ 44,  44,  44],
        [ 44,  44,  44],
        [ 43,  43,  43],
        ..., 
        [136, 136, 136],
        [134, 134, 134],
        [132, 132,